---
name: "Dotenv-vault action"
description: "Download '.env.$ENVIRONMENT' from dotenv.org (dotenv-vault)."
author: "Zdenek Lapes"
inputs:
  stage:
    description: "Stage to download .env from dotenv-vault"
    required: true
    default: "ci"
  move:
    description: "Move .env.${STAGE} to .env"
    required: false
    default: "true"
  dotenvMe:
    description: "dotenv-vault token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: npx -y dotenv-vault@latest pull ${{ inputs.stage }} --dotenvMe=${{ inputs.dotenvMe }} --yes
      shell: bash
    - run: mv .env.ci .env
      if: ${{ inputs.move == 'true' }}
      shell: bash
    - uses: webiny/action-post-run@3.1.0
      with:
        run: find . -iname ".env*" -type f -delete
