---
name: "Dotenv-vault action to directory"
description: "Download '.env.$ENVIRONMENT' from dotenv.org (dotenv-vault)."
author: "Zdenek Lapes, Khanh Nguyen"
inputs:
  stage:
    description: "Stage to download .env from dotenv-vault"
    required: true
    default: "ci"
  dotenvMe:
    description: "dotenv-vault token"
    required: true
  delete:
    description: "Delete .env files after dotenv-vault pull"
    required: false
    default: "true"
  directory:
    description: "Directory to download .env from dotenv-vault"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: npx -y dotenv-vault@latest pull ${{ inputs.stage }} --dotenvMe=${{ inputs.dotenvMe }} --yes
      working-directory: ${{ inputs.directory }}
      shell: bash
    - uses: webiny/action-post-run@3.1.0
      if: ${{ inputs.delete == 'true' }}
      with:
        run: find . -iname ".env*" -type f -delete

branding:
  icon: 'arrow-down-circle'
  color: 'yellow'