name: test-workflow

on:
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  test-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          dotenvMe: ${{ secrets.DOTENV_ME }}
          stage: "ci"
          move: "true"
